# Generated by Django 2.2.7 on 2019-12-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_otp',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
